name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: gcc install
      run: sudo apt-get install software-properties-common -y && sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install build-essential -y && sudo apt clean && sudo apt autoclean
    - name: make install
      run: make install
