name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: gcc install
      run: apt-get instal software-properties-common -y && add-apt-repository universe && apt-get update && apt-get install build-essential -y && apt clean && apt autoclean
    - name: make install
      run: make install
